# Generated by Django 4.2.3 on 2023-07-13 10:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ping_service", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="addressmodel",
            name="ip",
            field=models.CharField(default="0.0.0.0", editable=False, max_length=46),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="addressmodel",
            name="url",
            field=models.CharField(max_length=80, unique=True),
        ),
    ]
