# Generated by Django 4.2.3 on 2023-07-13 09:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("ping_service", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="addressmodel",
            name="pings",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="pinged_address",
                to="ping_service.pingmodel",
            ),
        ),
        migrations.AlterField(
            model_name="addressmodel",
            name="url",
            field=models.URLField(unique=True),
        ),
    ]
